### Get User
GET http://localhost:3001/accounts/auth

### Get User
GET http://localhost:3001/accounts/1709028201282

### Get User
GET http://localhost:3001/accounts/all

### Create account 
POST http://localhost:3001/accounts/create
Content-Type: application/json

### Login
POST http://localhost:3001/accounts/auth/login
Content-Type: application/json

{
  "email":"snapdevx@gmail.com",
  "password":"#33EXPort"
}

### Register
POST http://localhost:3001/accounts/register
Content-Type: application/json

{
  "email":"chefidelis@gmail.com",
  "phone":"+237691872554",
  "dob":"1987-03-11",
  "account":"96131258"
}

### Forgot
POST http://localhost:3001/accounts/password/forgot
Content-Type: application/json

{
  "email":"chefidelis@gmail.com",
  "dob":"1987-03-11",
  "account":"96131258"
}

### Check
GET http://localhost:3001/accounts/auth/password/expiry?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjE3MTg4ODAxMjYzMTMsImV4cGlyeSI6MTcxODg4NDg4MDAwNiwiaWF0IjoxNzE4ODgzMDgwfQ.BWjBAw7DkP2Hv4mW0OzcoU9YJVaXip3q-FYpuE6-8i0
Authorization: Bearer 

### Reset
POST http://localhost:3001/accounts/auth/password/reset
Authorization: Bearer 
Content-Type: application/json

{
  "email":"snapdevx@gmail.com",
  "password":"#33EXPort"
}

### Change password
PATCH http://localhost:3001/accounts/auth/password/change
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTcwOTAyODIwMTI4Mg.lTdUJuDE1d4AVPQyw0jBw2woeA0kRzt9HGi2jN7Bzzc
Content-Type: application/json

{
  "newpassword": "33EXPort",
  "password": "1234567890"
}

### Update
PATCH http://localhost:3001/accounts/1709028201282
Content-Type: application/json

{
  "profile.photo":"",
  "statement": [
    {
      "ref": "77011209",
      "date": "2024-02-26",
      "type": "credit",
      "amount": "2500000",
      "status": "complete",
      "desc": "Illuminati Operating Account ABA/TRC - *3002",
      "balance": "2500000"
    },
    {
      "ref": "77011387",
      "date": "2024-02-27",
      "type": "debit",
      "amount": "156345.23",
      "status": "complete",
      "desc": "Tax Account ABA/TRC - *1111",
      "balance": "2343654.77"
    }
  ]

}

### Delete
DELETE http://localhost:3001/accounts/1709028201282
