###
POST http://localhost:3001/payments/monetbil
Content-Type: application/json

{
  "phonenumber": "691872554",
  "amount": 10000,
  "operator": "CM_ORANGEMONEY",
  "currency": "XAF",
  "country": "CM",
  "first_name":"Fidelis Funwi",
  "last_name":"Che",
  "email": "chefidelis@gmail.com"
}
###
POST http://localhost:3001/payments/monetbil/place-payment
Content-Type: application/json

{
  "phonenumber": "651736264",
  "amount": 10000,
  "operator": "CM_MTNMOBILEMONEY",
  "currency": "XAF",
  "country": "CM",
  "first_name":"Fidelis Funwi",
  "last_name":"Che",
  "email": "chefidelis@gmail.com"
}

###
GET http://localhost:3001/payments/monetbil/check-payment/24122020413914922379
###
GET http://localhost:3001/payments/monetbil/payment-status/24122019323686114326

